### ISSUE TITLE
New dependencies required into packages.

### ISSUE THREAD

**Issue by uggla** [bcornec/python-redfish#31]
Hello Bruno,

It is time to review the dependencies. Python3 requirements and tests have introduced new dependencies.
New deps **in bold**.

Build & run deps :
pbr>=0.8
tortilla>=0.4.1
Jinja2>=2.7.3
Sphinx>=1.2.3     --> only for build
docopt>=0.6.2
simplejson>=3.8.1
**path.py>=5.2**   --> not in requirements.txt yet, but I will add it. (python-path.noarch pkg on Fedora)

(Python3 compat)
**future>=0.15.2**
**configparser>=3.3.0; python_version < '3'**   --> only for python 2

Tests only (so I will put them only in build requires part) :
**pytest>=2.6.4**
**coverage>=3.6**
**mock>=1.0.1**   --> not used yet
**docker-py>=1.1.0**
**path.py>=5.2**

**Comment by bcornec** [comment]
In order to ease the maintenance of packages, is it possible to modify requirements.txt in order to order the deps:

```
# Python 2&3 build deps
mod1
mod2
# Python 2&3 run deps
mod1 
mod3
# Python2 only build deps
...
# Python3 only build deps
...
# Python2 only run deps
...
# Python3 only run deps
...
```

Also being dependent on mock for tests seems not a so good idea as this is really fedora specific and won't allow to have a similar approach for other rpm based distros., nor for deb ones. We should find a way to have standard tests, not one specific to just one distro here, or modularize it.

**Comment by uggla** [comment]
:)
I understand the confusion. Mock is not the Ferora's mock. This is a really convenient python module to do some mockup opbject. So not specific to Fedora.
Regarding the requirement.txt, I don't see issues to sort it differently.

**Comment by bcornec** [comment]
In order to fix deps in packages we need some minimal versions, as tested on mageia 5:

python-nose-1.3.7
python-requests-2.9.1
python-urllib3-1.13.1
python-future-0.15.2

**Comment by bcornec** [comment]
All done except nose as I do not seem to need it for now. Test part not updated so not done yet.
