### ISSUE TITLE
Create RHEL7 python packages for python-redfish dependencies

### ISSUE THREAD

**Issue by uggla** [bcornec/python-redfish#45]
As RHEL 7 should be one of our target distribution for our POC, we need to create the rpms for python-redfish dependencies. Ex : tortilla.
I already own the repo for that within Epel.
Work needed is to modify the .spec used by Fedora to RHEL7 as the macros are not the same.

**Comment by bcornec** [comment]
For that we need some dependencies:

python-colorclass 1.2.0+ (René in CentoS 7 EPEL)
python-configparser 3.5.0b2 (OK)
python-docopt 0.6.2 (Bruno in local repo)
python-formats 0.1.1  (René in CentoS 7 EPEL)
python-pygments 2.0.2 (Bruno in local repo)
python-requests 2.9.1 (Bruno in local repo)
python-setuptools 19.6.2 (Bruno in local repo)
python-simplejson 3.8.1 (Bruno in local repo)
python-snowballstemmer 1.2.0 (Bruno in local repo)
python-sphinx 1.3.1 (Bruno in local repo)
python-sphinx-theme-alabaster 0.7.6 (Bruno in local repo) 
python-sphinx_rtd_theme 0.1.9 (Bruno in local repo)
python-tortilla 0.4.1 (René in CentoS 7 EPEL)
python-urllib3 1.13.1 (Bruno in local repo)

**Comment by bcornec** [comment]
Tonight work is available at ftp://ftp.mondorescue.org/centos/7/x86_64/:
python-mock-1.3.0-1.el7.noarch.rpm
python-pkg-resources-19.6.2-1.el7.noarch.rpm
python-pygments-2.0.2-1.el7.noarch.rpm
python-requests-2.9.1-1.el7.noarch.rpm
python-setuptools-19.6.2-1.el7.noarch.rpm
python-snowballstemmer-1.2.0-1.el7.noarch.rpm
python-sphinx-theme-alabaster-0.7.6-1.el7.noarch.rpm
python-sphinx_rtd_theme-0.1.9-1.el7.noarch.rpm
python-urllib3-1.13.1-1.el7.noarch.rpm

Still some pkgs to go !

**Comment by bcornec** [comment]
New packages available (and fixes for some of yesterday as well):
python-babel-2.3.4-1.el7.noarch.rpm
python-docopt-0.6.2-1.el7.noarch.rpm
python-funcsigs-0.4-1.el7.noarch.rpm
python-pbr-1.8.1-1.el7.noarch.rpm
python-pytest-2.8.2-1.el7.noarch.rpm
python-pytz-2016.3-1.el7.noarch.rpm
python-simplejson-3.8.1-1.el7.x86_64.rpm
python-sphinx-1.3.1-1.el7.noarch.rpm

I now have all my deps available.

**Comment by bcornec** [comment]
In order to progress on the PoC, I've quickly pushed as well the 3 other missing rpms to the repo, so now we can have all python-redfish deps for el7 at hand:
python-colorclass-1.2.0-1.el7.noarch.rpm
python-formats-0.1.1-1.el7.noarch.rpm
python-tortilla-0.4.1-1.el7.noarch.rpm

And I also added a ussung one in our first list:
python-future-0.15.2-1.el7.noarch.rpm

**Comment by bcornec** [comment]
After fixing some of the previous packags for deps and adding more packages:
texlive-upquote-2012-38.20130427_r30134.el7.noarch.rpm (as this is missing in the version on el7 !)
python-jinja2-2.8-1.el7.noarch.rpm

I've been able to finally produce a native python-redfish package for CentOS 7 using project-builder.org
NB: In order to install all these packages you'll have to use yum install --nogpgcheck as they are not signed.

You can test it under ftp://ftp.mondorescue.org/test/centos/7/x86_64/python-redfish-0.420160520014518-0.el7.noarch.rpm

In order to have it, we should also accept the PR #74 which fixes the build.

Will start using it now on the PoC platform.

**Comment by bcornec** [comment]
With that last fix the centos 7 package can be installed with all its deps on a CentOS 7 system and redfish-client can be launched.
Can be closed ASA PR is merged.

**Comment by bcornec** [comment]
CLosed with #74
